@baseUrl = http://localhost:3000

# ROTAS

### Recados all
GET {{baseUrl}}/recados

### Recados unique
GET {{baseUrl}}/recados/1

### Recados usanso query parameters
GET {{baseUrl}}/recados/usandoQuery/?try=10&user=teste&offset=100

### Post
POST  {{baseUrl}}/recados
Content-Type: application/json

{
  "texto": "oiiiii tudo bem?",
  "de": "rafa",
  "para": "aroldo" 
}

### Patch
PATCH  {{baseUrl}}/recados/3
Content-Type: application/json

{
  "texto": "ATUALIZAR teste",
  "de": "hehehehehe",
  "para": "hjvbsdjha"
}

### Delete
DELETE  {{baseUrl}}/recados/4
